// <auto-generated />
using Exchange.Api.Models.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Exchange.UI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210202175954_initialMigratio")]
    partial class initialMigratio
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Exchange.Api.Models.CurrencyModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("BankNoteBuying")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BanknoteSelling")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CrossRateUsd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrencyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ForexBuying")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("ForexSelling")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Unit")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("CurrencyModels");
                });
#pragma warning restore 612, 618
        }
    }
}
